### ISSUE TITLE
Integer number

### ISSUE THREAD

**Issue by alhejaj** [tisimst/pyswarm#7]
Hi 

I wonder how we can be able to generate integer number and short float numbers?

Regards
Sam

**Comment by tisimst** [comment]
That's not currently built into the package, nor do I know if I'll ever get to implementing such a mechanism. So, you'll need to define your own mechanism for rounding or mapping floats to integers as a first step in your own functions since the optimizer will only provide you with float input values and expects you to give it float output values. Whatever you do in-between is up to you.
